### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by sven941112** [viviRG2024/PINNGNN#2]
Thank you for your reply. But I cannot download the dataset since it shows "Access denied". Maybe it requires your approval. Thank you for your help.
![1725901679955](https://github.com/user-attachments/assets/48da411b-cdbc-4683-ad5c-97b036e34f70)

**Comment by alphonse-lin** [comment]
So sorry for the misleading. Apologize for that, I have updated the download link, you can have a look right now. However, I only upload PEMS04 and PEMS08, if you need other cities traffic flow data, please come and visit this website: https://figshare.com/articles/dataset/Integrated_Urban_Traffic-Flood_IUTF_Dataset/26870329?file=48881053
